name: to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  cloud_firestore: ^5.2.1
  device_preview: ^1.2.0
  dio: ^5.5.0+1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  lottie: ^3.1.2
  mocktail: ^1.0.4
  page_transition: ^2.1.0
  path: ^1.9.0
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.3.3+1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon_1.png"
  adaptive_icon_background: "#FFFFFF"
